<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../DBAForge.Application/DBAForge.Application.csproj" />
    <ProjectReference Include="../DBAForge.Infrastructure/DBAForge.Infrastructure.csproj" />
    <ProjectReference Include="../DBAForge.Contracts/DBAForge.Contracts.csproj" />
  </ItemGroup>
</Project>
